
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 28 22:53:29 BRT 2017
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int EQUALITY = 15;
  public static final int ELSE = 18;
  public static final int CLOSE = 9;
  public static final int THEN = 19;
  public static final int EQUAL = 10;
  public static final int ENDSTMT = 11;
  public static final int DIVISION = 5;
  public static final int SUM = 2;
  public static final int TRUE = 20;
  public static final int IF = 17;
  public static final int ID = 6;
  public static final int COMMA = 12;
  public static final int LESSTHAN = 14;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 4;
  public static final int DEF = 16;
  public static final int FALSE = 21;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int INTEGER = 7;
  public static final int OPEN = 8;
  public static final int GREATERTHAN = 13;
}

