
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ELSE = 15;
  public static final int CLOSE = 9;
  public static final int EQUAL = 12;
  public static final int THEN = 16;
  public static final int ENDSTMT = 17;
  public static final int DIVISION = 5;
  public static final int SUM = 2;
  public static final int IF = 14;
  public static final int ID = 6;
  public static final int COMMA = 7;
  public static final int LESSTHAN = 11;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 4;
  public static final int DEF = 13;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int INTEGER = 18;
  public static final int OPEN = 8;
  public static final int GREATERTHAN = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUM",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "ID",
  "COMMA",
  "OPEN",
  "CLOSE",
  "GREATERTHAN",
  "LESSTHAN",
  "EQUAL",
  "DEF",
  "IF",
  "ELSE",
  "THEN",
  "ENDSTMT",
  "INTEGER"
  };
}

