
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 01 01:45:54 BRT 2017
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int EQUALITY = 14;
  public static final int ELSE = 17;
  public static final int CLOSE = 11;
  public static final int THEN = 18;
  public static final int EQUAL = 8;
  public static final int ENDSTMT = 19;
  public static final int DIVISION = 5;
  public static final int SUM = 2;
  public static final int IF = 16;
  public static final int ID = 6;
  public static final int COMMA = 9;
  public static final int LESSTHAN = 13;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 4;
  public static final int DEF = 15;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int INTEGER = 7;
  public static final int OPEN = 10;
  public static final int GREATERTHAN = 12;
}

